--- #YAML:1.0
name:               GStreamer-Interfaces
version:            0.05
abstract:           Perl interface to the GStreamer Interfaces library
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0.205
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1.07
    Glib:                 1.180
    GStreamer:            0.06
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Depends:    0.205
    ExtUtils::PkgConfig:  1.07
    Glib:                 1.180
    GStreamer:            0.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
