--- #YAML:1.0
name:                GStreamer-Interfaces
version:             0.04
abstract:            Perl interface to the GStreamer Interfaces library
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.205
    ExtUtils::PkgConfig:           1.07
    Glib:                          1.180
    GStreamer:                     0.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
configure_requires:
   GStreamer: 0.06
   ExtUtils::Depends: 0.205
   Glib: 1.180
   ExtUtils::PkgConfig: 1.07
