# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GStreamer-Interfaces
version:      0.02
version_from: Interfaces.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.205
    ExtUtils::PkgConfig:           1.07
    Glib:                          1.103
    GStreamer:                     0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
